#!/bin/bash
set -e

# Gen Serving Gateway - Interactive Backend Setup Script
# This script helps configure AI model backends for the gateway

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
CONFIG_DIR="${PROJECT_ROOT}/config"
BACKENDS_CONFIG="${CONFIG_DIR}/backends.yaml"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
MAGENTA='\033[0;35m'
NC='\033[0m'
BOLD='\033[1m'

# Logging functions
log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }
log_step() { echo -e "${BLUE}[STEP]${NC} $1"; }

# Print banner
print_banner() {
    echo -e "${CYAN}"
    echo "╔══════════════════════════════════════════════════════════╗"
    echo "║                                                          ║"
    echo "║       ${BOLD}Gen Serving Gateway - Backend Setup${NC}${CYAN}              ║"
    echo "║                                                          ║"
    echo "║   Configure AI model backends for image & text          ║"
    echo "║   generation services                                    ║"
    echo "║                                                          ║"
    echo "╚══════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
}

# Print menu
print_menu() {
    echo ""
    echo -e "${BOLD}Select an option:${NC}"
    echo ""
    echo -e "  ${CYAN}[1]${NC} Add Image Generation Backend ${MAGENTA}(SD, DALL-E, ComfyUI...)${NC}"
    echo -e "  ${CYAN}[2]${NC} Add Text Generation Backend ${MAGENTA}(LLM, Chat, OpenAI...)${NC}"
    echo -e "  ${CYAN}[3]${NC} List Current Backends"
    echo -e "  ${CYAN}[4]${NC} Remove Backend"
    echo -e "  ${CYAN}[5]${NC} Test Backend Connection"
    echo -e "  ${CYAN}[6]${NC} Load from Existing YAML"
    echo -e "  ${CYAN}[7]${NC} Export Configuration"
    echo ""
    echo -e "  ${CYAN}[0]${NC} Exit and Save"
    echo ""
}

# Initialize config if not exists
init_config() {
    if [[ ! -f "$BACKENDS_CONFIG" ]]; then
        log_step "Creating new backends configuration..."
        mkdir -p "$CONFIG_DIR"
        cat > "$BACKENDS_CONFIG" << 'EOF'
# Gen Serving Gateway - Backend Configuration
# Generated by setup-backends.sh

version: "1.0"

defaults:
  health_check:
    interval_secs: 30
    timeout_secs: 5
  connection:
    timeout_ms: 60000
    retry_count: 3

backends:
  image: []
  text: []
  grpc: []

routing:
  default_strategy: round_robin
  model_mappings: {}
  fallbacks: {}
EOF
        log_info "Created new configuration at $BACKENDS_CONFIG"
    fi
}

# Read user input with default
read_input() {
    local prompt="$1"
    local default="$2"
    local result
    
    if [[ -n "$default" ]]; then
        read -p "$prompt [$default]: " result
        result="${result:-$default}"
    else
        read -p "$prompt: " result
    fi
    
    echo "$result"
}

# Read yes/no input
read_yes_no() {
    local prompt="$1"
    local default="${2:-y}"
    local result
    
    while true; do
        read -p "$prompt [${default}]: " result
        result="${result:-$default}"
        result=$(echo "$result" | tr '[:upper:]' '[:lower:]')
        
        case "$result" in
            y|yes) echo "true"; return 0 ;;
            n|no) echo "false"; return 0 ;;
            *) echo -e "${RED}Please enter y or n${NC}" >&2 ;;
        esac
    done
}

# Select from options
select_option() {
    local prompt="$1"
    shift
    local options=("$@")
    local choice
    
    echo -e "\n${BOLD}$prompt${NC}"
    for i in "${!options[@]}"; do
        echo -e "  ${CYAN}[$((i+1))]${NC} ${options[$i]}"
    done
    
    while true; do
        read -p "Enter choice [1-${#options[@]}]: " choice
        if [[ "$choice" =~ ^[0-9]+$ ]] && [[ "$choice" -ge 1 ]] && [[ "$choice" -le "${#options[@]}" ]]; then
            echo "${options[$((choice-1))]}"
            return 0
        fi
        echo -e "${RED}Invalid choice. Please try again.${NC}"
    done
}

# Add image backend
add_image_backend() {
    echo ""
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${BOLD}       Add Image Generation Backend${NC}"
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""
    
    # Backend type selection
    local backend_type=$(select_option "Select image backend type:" \
        "stable-diffusion (Automatic1111 WebUI)" \
        "comfyui (ComfyUI)" \
        "dalle (OpenAI DALL-E)" \
        "midjourney (Midjourney API)" \
        "custom (Custom HTTP/gRPC)")
    
    # Extract short name
    local type_name=$(echo "$backend_type" | cut -d' ' -f1)
    
    # Basic info
    echo ""
    local name=$(read_input "Backend name" "$type_name-1")
    
    # Endpoint configuration
    echo ""
    log_step "Endpoint Configuration"
    local endpoint
    case "$type_name" in
        stable-diffusion)
            endpoint=$(read_input "WebUI URL" "http://localhost:7860")
            ;;
        comfyui)
            endpoint=$(read_input "ComfyUI URL" "http://localhost:8188")
            ;;
        dalle)
            endpoint=$(read_input "OpenAI API URL" "https://api.openai.com/v1")
            ;;
        *)
            endpoint=$(read_input "Backend URL" "http://localhost:8080")
            ;;
    esac
    
    # Protocol
    local protocol="http"
    if [[ "$type_name" == "dalle" ]]; then
        protocol="openai"
    fi
    
    # Authentication
    echo ""
    log_step "Authentication Configuration"
    local auth_type="none"
    local token_env=""
    
    if [[ "$type_name" == "dalle" ]] || [[ "$type_name" == "midjourney" ]]; then
        auth_type="bearer"
        token_env=$(read_input "API Key environment variable" "OPENAI_API_KEY")
    else
        local needs_auth=$(read_yes_no "Does this backend require authentication?" "n")
        if [[ "$needs_auth" == "true" ]]; then
            auth_type=$(select_option "Select authentication type:" "bearer" "api_key" "header")
            auth_type=$(echo "$auth_type" | cut -d' ' -f1)
            token_env=$(read_input "Token environment variable name" "")
        fi
    fi
    
    # Health check
    echo ""
    log_step "Health Check Configuration"
    local health_path
    case "$type_name" in
        stable-diffusion) health_path="/internal/ping" ;;
        comfyui) health_path="/system_stats" ;;
        *) health_path="/health" ;;
    esac
    health_path=$(read_input "Health check path" "$health_path")
    local health_interval=$(read_input "Health check interval (seconds)" "30")
    
    # Models
    echo ""
    log_step "Model Configuration"
    local models=""
    if [[ "$type_name" == "dalle" ]]; then
        models=$(read_input "Supported models (comma-separated)" "dall-e-3,dall-e-2")
    else
        models=$(read_input "Supported models (comma-separated, optional)" "")
    fi
    
    # Generate YAML entry
    local yaml_entry="    - name: $name
      type: image
      protocol: $protocol
      enabled: true
      endpoints:
        - \"$endpoint\"
      auth:
        type: $auth_type"
    
    if [[ -n "$token_env" ]]; then
        yaml_entry="$yaml_entry
        token_env: $token_env"
    fi
    
    yaml_entry="$yaml_entry
      health_check:
        path: $health_path
        interval_secs: $health_interval
      load_balancer:
        strategy: round_robin
        weight: 1"
    
    if [[ -n "$models" ]]; then
        yaml_entry="$yaml_entry
      models:"
        IFS=',' read -ra model_array <<< "$models"
        for model in "${model_array[@]}"; do
            yaml_entry="$yaml_entry
        - $(echo $model | xargs)"
        done
    fi
    
    # Save to config
    echo ""
    log_step "Saving configuration..."
    
    # Find image section and append
    python3 << EOF
import yaml

with open('$BACKENDS_CONFIG', 'r') as f:
    config = yaml.safe_load(f)

if config is None:
    config = {'version': '1.0', 'backends': {'image': [], 'text': [], 'grpc': []}}

if 'backends' not in config:
    config['backends'] = {'image': [], 'text': [], 'grpc': []}
    
if 'image' not in config['backends']:
    config['backends']['image'] = []

new_backend = {
    'name': '$name',
    'type': 'image',
    'protocol': '$protocol',
    'enabled': True,
    'endpoints': ['$endpoint'],
    'auth': {
        'type': '$auth_type'
    },
    'health_check': {
        'path': '$health_path',
        'interval_secs': $health_interval
    },
    'load_balancer': {
        'strategy': 'round_robin',
        'weight': 1
    }
}

if '$token_env':
    new_backend['auth']['token_env'] = '$token_env'

if '$models':
    new_backend['models'] = [m.strip() for m in '$models'.split(',')]

config['backends']['image'].append(new_backend)

with open('$BACKENDS_CONFIG', 'w') as f:
    yaml.dump(config, f, default_flow_style=False, sort_keys=False, allow_unicode=True)
EOF
    
    log_info "Image backend '$name' added successfully!"
}

# Add text backend
add_text_backend() {
    echo ""
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${BOLD}       Add Text Generation Backend${NC}"
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""
    
    # Backend type selection
    local backend_type=$(select_option "Select text backend type:" \
        "ollama (Ollama - Local LLM)" \
        "openai (OpenAI API - GPT models)" \
        "anthropic (Anthropic API - Claude)" \
        "vllm (vLLM Server)" \
        "tgi (Text Generation Inference)" \
        "together (Together AI)" \
        "custom (Custom OpenAI-compatible)")
    
    local type_name=$(echo "$backend_type" | cut -d' ' -f1)
    
    # Basic info
    echo ""
    local name=$(read_input "Backend name" "$type_name-1")
    
    # Endpoint configuration
    echo ""
    log_step "Endpoint Configuration"
    local endpoint
    local protocol="openai"
    
    case "$type_name" in
        ollama)
            endpoint=$(read_input "Ollama URL" "http://localhost:11434/v1")
            ;;
        openai)
            endpoint=$(read_input "OpenAI API URL" "https://api.openai.com/v1")
            ;;
        anthropic)
            endpoint=$(read_input "Anthropic API URL" "https://api.anthropic.com/v1")
            protocol="anthropic"
            ;;
        vllm)
            endpoint=$(read_input "vLLM Server URL" "http://localhost:8000/v1")
            ;;
        tgi)
            endpoint=$(read_input "TGI Server URL" "http://localhost:3000")
            protocol="tgi"
            ;;
        together)
            endpoint=$(read_input "Together AI URL" "https://api.together.xyz/v1")
            ;;
        *)
            endpoint=$(read_input "Backend URL" "http://localhost:8080/v1")
            ;;
    esac
    
    # Authentication
    echo ""
    log_step "Authentication Configuration"
    local auth_type="none"
    local token_env=""
    local header_name=""
    
    case "$type_name" in
        openai|together)
            auth_type="bearer"
            token_env=$(read_input "API Key environment variable" "OPENAI_API_KEY")
            ;;
        anthropic)
            auth_type="header"
            header_name="x-api-key"
            token_env=$(read_input "API Key environment variable" "ANTHROPIC_API_KEY")
            ;;
        ollama|vllm|tgi)
            local needs_auth=$(read_yes_no "Does this backend require authentication?" "n")
            if [[ "$needs_auth" == "true" ]]; then
                auth_type="bearer"
                token_env=$(read_input "Token environment variable name" "")
            fi
            ;;
        *)
            local needs_auth=$(read_yes_no "Does this backend require authentication?" "n")
            if [[ "$needs_auth" == "true" ]]; then
                auth_type=$(select_option "Select authentication type:" "bearer" "api_key" "header")
                auth_type=$(echo "$auth_type" | cut -d' ' -f1)
                token_env=$(read_input "Token environment variable name" "")
            fi
            ;;
    esac
    
    # Health check
    echo ""
    log_step "Health Check Configuration"
    local health_path
    case "$type_name" in
        ollama) health_path="/api/tags" ;;
        vllm|tgi) health_path="/health" ;;
        *) health_path="/models" ;;
    esac
    health_path=$(read_input "Health check path" "$health_path")
    local health_interval=$(read_input "Health check interval (seconds)" "30")
    
    # Models
    echo ""
    log_step "Model Configuration"
    local models=""
    case "$type_name" in
        ollama)
            models=$(read_input "Available models (comma-separated)" "llama3,mistral,codellama")
            ;;
        openai)
            models=$(read_input "Available models (comma-separated)" "gpt-4,gpt-4-turbo,gpt-3.5-turbo")
            ;;
        anthropic)
            models=$(read_input "Available models (comma-separated)" "claude-3-opus-20240229,claude-3-sonnet-20240229,claude-3-haiku-20240307")
            ;;
        *)
            models=$(read_input "Available models (comma-separated)" "")
            ;;
    esac
    
    # Capabilities
    echo ""
    log_step "Capabilities"
    local caps_chat=$(read_yes_no "Supports chat completions?" "y")
    local caps_completion=$(read_yes_no "Supports text completions?" "y")
    local capabilities=""
    [[ "$caps_chat" == "true" ]] && capabilities="chat"
    [[ "$caps_completion" == "true" ]] && capabilities="${capabilities:+$capabilities,}completion"
    
    # Save to config
    echo ""
    log_step "Saving configuration..."
    
    python3 << EOF
import yaml

with open('$BACKENDS_CONFIG', 'r') as f:
    config = yaml.safe_load(f)

if config is None:
    config = {'version': '1.0', 'backends': {'image': [], 'text': [], 'grpc': []}}

if 'backends' not in config:
    config['backends'] = {'image': [], 'text': [], 'grpc': []}
    
if 'text' not in config['backends']:
    config['backends']['text'] = []

new_backend = {
    'name': '$name',
    'type': 'text',
    'protocol': '$protocol',
    'enabled': True,
    'endpoints': ['$endpoint'],
    'auth': {
        'type': '$auth_type'
    },
    'health_check': {
        'path': '$health_path',
        'interval_secs': $health_interval
    },
    'load_balancer': {
        'strategy': 'round_robin',
        'weight': 1
    }
}

if '$token_env':
    new_backend['auth']['token_env'] = '$token_env'

if '$header_name':
    new_backend['auth']['header_name'] = '$header_name'

if '$models':
    new_backend['models'] = [m.strip() for m in '$models'.split(',')]

if '$capabilities':
    new_backend['capabilities'] = [c.strip() for c in '$capabilities'.split(',')]

config['backends']['text'].append(new_backend)

with open('$BACKENDS_CONFIG', 'w') as f:
    yaml.dump(config, f, default_flow_style=False, sort_keys=False, allow_unicode=True)
EOF
    
    log_info "Text backend '$name' added successfully!"
}

# List backends
list_backends() {
    echo ""
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${BOLD}       Current Backend Configuration${NC}"
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    
    python3 << 'EOF'
import yaml
import sys

try:
    with open('$BACKENDS_CONFIG', 'r') as f:
        config = yaml.safe_load(f)
    
    if not config or 'backends' not in config:
        print("\n  No backends configured.\n")
        sys.exit(0)
    
    backends = config['backends']
    
    # Image backends
    print("\n  \033[1;35m📷 Image Generation Backends:\033[0m")
    if backends.get('image'):
        for i, b in enumerate(backends['image'], 1):
            status = "✅" if b.get('enabled', True) else "❌"
            print(f"    {status} [{i}] {b['name']}")
            print(f"        Protocol: {b.get('protocol', 'http')}")
            print(f"        Endpoints: {', '.join(b.get('endpoints', []))}")
            if b.get('models'):
                print(f"        Models: {', '.join(b['models'])}")
    else:
        print("    (none)")
    
    # Text backends
    print("\n  \033[1;35m💬 Text Generation Backends:\033[0m")
    if backends.get('text'):
        for i, b in enumerate(backends['text'], 1):
            status = "✅" if b.get('enabled', True) else "❌"
            print(f"    {status} [{i}] {b['name']}")
            print(f"        Protocol: {b.get('protocol', 'openai')}")
            print(f"        Endpoints: {', '.join(b.get('endpoints', []))}")
            if b.get('models'):
                print(f"        Models: {', '.join(b['models'])}")
            if b.get('capabilities'):
                print(f"        Capabilities: {', '.join(b['capabilities'])}")
    else:
        print("    (none)")
    
    # gRPC backends
    if backends.get('grpc'):
        print("\n  \033[1;35m🔌 gRPC Backends:\033[0m")
        for i, b in enumerate(backends['grpc'], 1):
            status = "✅" if b.get('enabled', True) else "❌"
            print(f"    {status} [{i}] {b['name']}")
            print(f"        Endpoints: {', '.join(b.get('endpoints', []))}")
    
    print()

except FileNotFoundError:
    print("\n  Configuration file not found. Run setup first.\n")
except Exception as e:
    print(f"\n  Error reading configuration: {e}\n")
EOF
}

# Remove backend
remove_backend() {
    echo ""
    list_backends
    
    local backend_type=$(select_option "Select backend category to remove from:" "image" "text" "grpc")
    
    python3 << EOF
import yaml

with open('$BACKENDS_CONFIG', 'r') as f:
    config = yaml.safe_load(f)

backends = config.get('backends', {}).get('$backend_type', [])
if not backends:
    print("\n  No backends in this category.\n")
    exit(0)

print("\nBackends in $backend_type category:")
for i, b in enumerate(backends, 1):
    print(f"  [{i}] {b['name']}")
print(f"  [0] Cancel")

choice = input("\nEnter number to remove: ")
try:
    idx = int(choice)
    if idx == 0:
        print("Cancelled.")
        exit(0)
    if 1 <= idx <= len(backends):
        removed = backends.pop(idx - 1)
        config['backends']['$backend_type'] = backends
        with open('$BACKENDS_CONFIG', 'w') as f:
            yaml.dump(config, f, default_flow_style=False, sort_keys=False, allow_unicode=True)
        print(f"\n✅ Removed backend: {removed['name']}")
    else:
        print("Invalid selection.")
except ValueError:
    print("Invalid input.")
EOF
}

# Test backend connection
test_backend() {
    echo ""
    log_step "Testing backend connections..."
    
    python3 << 'EOF'
import yaml
import urllib.request
import urllib.error
import ssl

# Disable SSL verification for testing
ctx = ssl.create_default_context()
ctx.check_hostname = False
ctx.verify_mode = ssl.CERT_NONE

with open('$BACKENDS_CONFIG', 'r') as f:
    config = yaml.safe_load(f)

if not config or 'backends' not in config:
    print("\n  No backends to test.\n")
    exit(0)

def test_endpoint(name, endpoint, health_path):
    url = endpoint.rstrip('/') + health_path
    try:
        req = urllib.request.Request(url, method='GET')
        req.add_header('User-Agent', 'gen-gateway-test/1.0')
        response = urllib.request.urlopen(req, timeout=5, context=ctx)
        return True, response.status
    except urllib.error.HTTPError as e:
        # 401/403 might still mean server is up
        if e.code in [401, 403]:
            return True, f"{e.code} (auth required)"
        return False, str(e.code)
    except Exception as e:
        return False, str(e)

backends = config['backends']
print("\n  Testing backend connections...\n")

for category in ['image', 'text', 'grpc']:
    if not backends.get(category):
        continue
    
    print(f"  \033[1m{category.upper()} BACKENDS:\033[0m")
    
    for b in backends[category]:
        if not b.get('enabled', True):
            print(f"    ⏭️  {b['name']}: DISABLED")
            continue
        
        endpoint = b.get('endpoints', [''])[0]
        health_path = b.get('health_check', {}).get('path', '/health')
        
        success, result = test_endpoint(b['name'], endpoint, health_path)
        
        if success:
            print(f"    ✅ {b['name']}: OK ({result})")
        else:
            print(f"    ❌ {b['name']}: FAILED ({result})")
    
    print()
EOF
}

# Export configuration
export_config() {
    echo ""
    log_step "Current configuration:"
    echo ""
    cat "$BACKENDS_CONFIG"
    echo ""
    
    local export_path=$(read_input "Export to file (leave empty to skip)" "")
    if [[ -n "$export_path" ]]; then
        cp "$BACKENDS_CONFIG" "$export_path"
        log_info "Configuration exported to $export_path"
    fi
}

# Load from existing YAML
load_from_yaml() {
    echo ""
    local yaml_path=$(read_input "Enter path to YAML file" "")
    
    if [[ ! -f "$yaml_path" ]]; then
        log_error "File not found: $yaml_path"
        return 1
    fi
    
    # Validate YAML
    python3 << EOF
import yaml
import sys

try:
    with open('$yaml_path', 'r') as f:
        config = yaml.safe_load(f)
    
    if 'backends' not in config:
        print("Warning: No 'backends' section found in YAML")
    
    print("YAML is valid.")
except Exception as e:
    print(f"Error: {e}")
    sys.exit(1)
EOF
    
    if [[ $? -eq 0 ]]; then
        local overwrite=$(read_yes_no "Overwrite current configuration?" "n")
        if [[ "$overwrite" == "true" ]]; then
            cp "$yaml_path" "$BACKENDS_CONFIG"
            log_info "Configuration loaded from $yaml_path"
        else
            log_info "Operation cancelled."
        fi
    fi
}

# Non-interactive mode
non_interactive_setup() {
    local config_file="$1"
    
    if [[ -n "$config_file" ]] && [[ -f "$config_file" ]]; then
        log_info "Loading configuration from $config_file..."
        cp "$config_file" "$BACKENDS_CONFIG"
        log_info "Configuration loaded successfully."
    else
        log_warn "No configuration file provided or file not found."
        log_info "Using default configuration."
    fi
}

# Main function
main() {
    # Parse arguments
    local non_interactive=false
    local config_file=""
    
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --non-interactive|-n)
                non_interactive=true
                shift
                ;;
            --config|-c)
                config_file="$2"
                shift 2
                ;;
            --help|-h)
                echo "Usage: $0 [OPTIONS]"
                echo ""
                echo "Options:"
                echo "  -n, --non-interactive   Run without prompts"
                echo "  -c, --config FILE       Load configuration from file"
                echo "  -h, --help             Show this help"
                exit 0
                ;;
            *)
                log_error "Unknown option: $1"
                exit 1
                ;;
        esac
    done
    
    # Initialize
    init_config
    
    # Non-interactive mode
    if [[ "$non_interactive" == true ]]; then
        non_interactive_setup "$config_file"
        exit 0
    fi
    
    # Interactive mode
    print_banner
    
    while true; do
        print_menu
        read -p "Enter your choice: " choice
        
        case "$choice" in
            1) add_image_backend ;;
            2) add_text_backend ;;
            3) list_backends ;;
            4) remove_backend ;;
            5) test_backend ;;
            6) load_from_yaml ;;
            7) export_config ;;
            0)
                echo ""
                log_info "Configuration saved to $BACKENDS_CONFIG"
                log_info "You can now start the gateway."
                echo ""
                exit 0
                ;;
            *)
                log_error "Invalid choice. Please try again."
                ;;
        esac
    done
}

main "$@"

